name: Hex

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Generate documentation
        run: rebar3 edoc

      - name: list dir
        run: ls -la
      - name: Setup rebar3 hex
        run: |
          mkdir -p ~/.config/rebar3/
          echo "{plugins, [rebar3_hex]}." > ~/.config/rebar3/rebar.config

      - name: Publish to hex.pm
        run: DEBUG=1 rebar3 hex publish --repo hexpm --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

      - name: Show dump head
        if: failure()
        run: head rebar3.crashdump

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: rebar3-dump
          path: rebar*
          if-no-files-found: ignore
